<a href="https://colab.research.google.com/github/josedasilva-Design/Curso_de_Machine_Learning/blob/main/Curso_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Curso Machine Learning**

Vamos aprender a usar a biblioteca Numpy para trabalhar com vetores e matrizes usando Python

Roteiro:
  1. Criando listas e arrays
  2. Operações com vetores
  3. Criando matrizes                        
  4. Operações com matrizes
  5. seleção e atribuição de valores

In [1]:
# impotar a biblioteca
import numpy as np

## **1. Criando litas e arrays**  

In [2]:
# criar uma lista simples
my_list = [0,1,2,3,4,5]

In [4]:
# criar um arrays com numpy
my_arry = np.array([0,1,2,3,4,5])

## **Verificar a diferença entre a lista e o array**

In [5]:
print(my_list)
print(my_arry)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [6]:
print(type(my_list))
print(type(my_arry))

<class 'list'>
<class 'numpy.ndarray'>


## **2. Operações com vetores**  

## **2.1 Operador de soma (+) e subtração (-)**

In [7]:
# fazer a operação de soma na lista
print(my_list + 1)

TypeError: can only concatenate list (not "int") to list

In [8]:
# fazer a operação de soma no array
print(my_arry +1)

[1 2 3 4 5 6]


In [9]:
# somar dois array
print(my_arry + my_arry)

[ 0  2  4  6  8 10]


In [10]:
# subtraido dois arrays
print(my_arry - my_arry)

[0 0 0 0 0 0]


## **2,2 Operador de multiplicação (*) e divisão (/)**

In [11]:
# fazer a operação de multiplicação na lista
print(my_list * 2)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [12]:
# fazer a opreração de multiplicação no array
print(my_arry * 2)

[ 0  2  4  6  8 10]


In [13]:
# fazer a operação de divisão no array
print(my_arry / 2)

[0.  0.5 1.  1.5 2.  2.5]


## **3. Criando matrizes**

## Uma matriz é uma estrutura composta de **m** linhas por **n** colunas.

In [15]:
# criando uma matriz a partir de listas
matrix_1 = np.array([my_list, my_list, my_list])
matrix_1

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [23]:
# criando uma matriz a partir de arrays
matrix_2 = np.array([my_arry, my_arry, my_arry])
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

## Em uma matriz todas as linhas contém a mesma quantidade de elementos.

In [49]:
# criar uma matriz com uma quantidade diferente de elementos na lista
matrix_3 = np.array([[1,2],[1,2],[1,2,],[1,2],[1,2,3]])
matrix_3

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [39]:
# criando uma mariz com valores zerados
matrix_4 = np.zeros((3,6))
matrix_4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## **4. Operações com matrizes**

# **4.1 Operador de soma(+) e subtração (-)**

In [40]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [41]:
# fazer operação de soma
matrix_2 + 3

array([[3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8]])

In [42]:
# fazer operação de subtrção
matrix_2 - 3

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [50]:
# visualizar novamente a matriz 3 mal formatada
matrix_3

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 3]])

In [51]:
# usar o operador de soma
matrix_3 + 3

array([[4, 5],
       [4, 5],
       [4, 5],
       [4, 5],
       [4, 6]])

## 4.2 Operador de multiplicação (*) e divisão (/)

In [52]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [53]:
# fazer a operação de multiplicação na matrix
matrix_2 * 2

array([[ 0,  2,  4,  6,  8, 10],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  2,  4,  6,  8, 10]])

In [56]:
# fazer a operação de divisão na matriz
matrix_2 / 2
matrix_2 / matrix_2


<ipython-input-56-580e4ab6a80f>:3: RuntimeWarning: invalid value encountered in divide
  matrix_2 / matrix_2


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.,  1.]])

## **5. Seleção e atribuição de valores**

## **5.1 Listas e vetores**

In [61]:
# criar  uma lista
print(my_list)

# selecionar o valor da lista na posição 3
print(my_list[3])

# selecionar o valor da lista na última posição
print(my_list[-1])

# mudar o valor da posição 0
my_list[0] = 6
print(my_list)



[6, 1, 2, 3, 4, 5]
3
5
[6, 1, 2, 3, 4, 5]


In [64]:
# Criar um arry
print(my_arry)

# selecionar o valor da lista na posição
print(my_arry[3])

# selecionar o valor da lista na última posição
print(my_arry[-1])

# mudar o valor da posição 0
my_arry[0] = 6
print(my_arry)

[6 1 2 3 4 5]
3
5
[6 1 2 3 4 5]


# **5.2. Matrizes**

In [65]:
# visualizar novamente a matriz 2
print(matrix_2)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [66]:
# selecionar o valor da matriz na posição 2.3
matrix_2[2,3]

3

In [67]:
# selecionar o último valor da matriz da linha 1
matrix_2[1,-1]

5

In [68]:
# mudar o valor da posição 0.0
matrix_2[0,0] = 6
matrix_2

array([[6, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])